### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by hoorayrui** [meiyor/Deep-Learning-Emotion-Decoding-using-EEG-data-from-Autism-individuals#1]
I fail to find dataset,can you send it again please

**Comment by meiyor** [comment]
To access the dataset you need send an email to Matthew D. Lerner, PhD at matthew.lerner@stonybrook.edu and check when he will have the dataset available for sharing. Unfortunately I don't have the permission for accessing the dataset now, so you need to communicate to Dr. Lerner first and see when he will have it available.

**Comment by hoorayrui** [comment]
Thank you！
